[package]
name = "nendi-derive"
version = "0.1.0"
edition = "2021"
description = "Proc macros for the Nendi CDC SDK"
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = { version = "2", features = ["full"] }
proc-macro2 = "1"
